addons:
  sauce_connect: true
language: node_js
node_js:
- 0.10
before_script:
- npm install -g grunt-cli
script:
- grunt
env:
  global:
  - secure: VTFvmKxgNjIdrZ36Ibhl/7onT+8cPHVcVIrTIbmtGQygVwkTgHW8MuuEOPdj8SojpACCpF82H/HbZF1dqQxcCDU0c0MKixcGrT+C70MI8mChutCc31f9tvpNAHkDoyveZLvlO99/ZVFGS+IQdmBkh8/jd/ekRxUCBqOS1DrYv8M=
  - secure: v4v2hkm9RYKJ7uP0J2jjf2xT0Mo9f20qsvrGlDd6mrPF+0R9JrahXKcuLkgzYCW+VnVj4dPr2KwWQJA4vsRzTGS4InqGYh9+jx1sonXibRgQBn3Nes5SwCrmq9JnAPl5HOehhk1l4sJc6MYKs6jh3kWf+5cLSZrcC7JonGiUgHM=
